// PROJECT
export const PROJECT_FORM = 'PROJECT_FORM'
export const GET_PROJECTS = 'GET_PROJECTS'
export const ADD_PROJECT = 'ADD_PROJECT'
export const VALIDATE_FORM = 'VALIDATE_FORM'
export const ACTUAL_PROJECT = 'ACTUAL_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'

// TASKS
export const TASKS_PROJECT = 'TASKS_PROJECT'
export const ADD_TASK = 'ADD_TASK'
export const TASK_ERROR = 'TASK_ERROR'
export const DELETE_TASK = 'DELETE_TASK'
export const CHANGE_STATUS = 'CHANGE_STATUS'
export const EDIT_TASK = 'EDIT_TASK'






